language: python

python:
  - "2.7"

sudo: required

install:
  - sudo pip install -r requirements-testing.txt
  - sudo pip install -e .

before_script:
  - sudo mkdir -p /usr/local/directadmin/conf
  - echo 'user=root' | sudo tee /usr/local/directadmin/conf/mysql.conf
  - echo 'passwd=' | sudo tee -a /usr/local/directadmin/conf/mysql.conf

script:
  - sudo py.test

after_success:
  - coveralls
