language: python

python:
  - "2.7"

sudo: required

install:
  - pip install coveralls 
  - pip install betamax
  - pip install -r requirements.txt
  #- python setup.py install

script:
  - sudo python setup.py nosetests

after_success:
  - coveralls
