language: python

python:
  - "2.7"

sudo: required

install:
  - sudo pip install -r requirements-testing.txt
  - sudo pip install -e .

script:
  - sudo py.test

after_script:
  - sudo py.test --cov-report term-missing --cov=server_check --cov-fail-under=95 tests/
